import type { LogoEntry } from "@/lib/content";

export const CLIENT_CATEGORIES = [
  "All",
  "Fashion & Lifestyle",
  "Banking & Finance",
  "FMCG & Food",
  "Automotive",
  "Real Estate",
  "Pharma & Wellness",
  "Industrial & Energy",
  "Technology",
  "Education",
] as const;

export type ClientCategory = (typeof CLIENT_CATEGORIES)[number];

export type ClientLogo = LogoEntry & {
  category: Exclude<ClientCategory, "All">;
};

export const FEATURED_CLIENT_SLUGS = [
  "lacoste",
  "nestle",
  "samsung",
  "khaadi",
  "hugo-boss",
  "hyundai",
  "allied-bank",
  "sapphire",
] as const;

export const CLIENT_CATEGORY_SLUGS: Record<
  Exclude<ClientCategory, "All">,
  readonly string[]
> = {
  "Fashion & Lifestyle": [
    "bata",
    "bareeze",
    "boss-home",
    "home-and-you",
    "hugo-boss",
    "i-and-k",
    "interloop",
    "khaadi",
    "lacoste",
    "laura-ashley",
    "maria-b",
    "martha-stewart",
    "michael-kors",
    "nautica",
    "next",
    "nicole-miller",
    "ralph-lauren",
    "sapphire",
    "tchibo",
    "ted-baker",
    "tommy-bahama",
    "tommy-hilfiger",
  ],
  "Banking & Finance": [
    "allied-bank",
    "askari-bank",
    "bank-of-punjab",
    "mcb-bank",
  ],
  "FMCG & Food": [
    "cola-next",
    "fauji-foods",
    "fresh-and-white",
    "golden-pearl",
    "goree",
    "hi-nutrition",
    "nestle",
    "noor-gold",
    "parley",
    "volka-foods",
  ],
  Automotive: ["hyundai", "jaecoo", "mg-motors", "millat-tractors", "proton"],
  "Real Estate": [
    "al-kabir-developers",
    "bahria",
    "bsm-developers",
    "cbd-punjab",
    "citi-housing",
    "citi-school",
    "etihad-town",
    "idap",
    "nishat-group",
    "safari-gardens",
    "union-developers",
  ],
  "Pharma & Wellness": [
    "herbiotics",
    "homeo-cure",
    "neutrifactor",
    "neutro-pharma",
  ],
  "Industrial & Energy": [
    "cci",
    "crescent-steel",
    "fatima-fertilizer",
    "fccl",
    "ffc",
    "go-petroleum",
    "hubco",
    "kapco",
    "kohat-cement",
    "les",
    "lucky-cement",
    "mughal-steel",
    "naveena-steel",
    "ogdc",
    "total-parco",
  ],
  Technology: ["huawei", "iac", "nugen", "ptc", "samsung", "wateen"],
  Education: ["gift-university", "lums", "umt"],
};

export const CLIENT_NAME_OVERRIDES: Record<string, string> = {
  "al-kabir-developers": "Al Kabir Developers",
  "allied-bank": "Allied Bank",
  "askari-bank": "Askari Bank",
  bahria: "Bahria Town",
  "bank-of-punjab": "Bank of Punjab",
  "boss-home": "BOSS Home",
  "bsm-developers": "BSM Developers",
  "cbd-punjab": "CBD Punjab",
  cci: "CCI",
  "citi-housing": "Citi Housing",
  "citi-school": "Citi School",
  "cola-next": "Cola Next",
  "crescent-steel": "Crescent Steel",
  "etihad-town": "Etihad Town",
  "fatima-fertilizer": "Fatima Fertilizer",
  "fauji-foods": "Fauji Foods",
  fccl: "FCCL",
  ffc: "FFC",
  "fresh-and-white": "Fresh & White",
  "gift-university": "Gift University",
  "go-petroleum": "Go Petroleum",
  "golden-pearl": "Golden Pearl",
  "hi-nutrition": "Hi Nutrition",
  "home-and-you": "Home & You",
  "homeo-cure": "Homeo Cure",
  hubco: "HUBCO",
  "hugo-boss": "Hugo Boss",
  huawei: "Huawei",
  hyundai: "Hyundai",
  iac: "IAC",
  "i-and-k": "I&K",
  idap: "IDAP",
  jaecoo: "JAECOO",
  kapco: "KAPCO",
  khaadi: "Khaadi",
  "kohat-cement": "Kohat Cement",
  lacoste: "Lacoste",
  "laura-ashley": "Laura Ashley",
  les: "LES",
  "lucky-cement": "Lucky Cement",
  lums: "LUMS",
  "maria-b": "Maria.B",
  "martha-stewart": "Martha Stewart",
  "mcb-bank": "MCB Bank",
  "mg-motors": "MG Motors",
  "michael-kors": "Michael Kors",
  "millat-tractors": "Millat Tractors",
  "mughal-steel": "Mughal Steel",
  "naveena-steel": "Naveena Steel",
  nestle: "Nestlé",
  neutrifactor: "Neutrifactor",
  "neutro-pharma": "Neutro Pharma",
  "nicole-miller": "Nicole Miller",
  "nishat-group": "Nishat Group",
  "noor-gold": "Noor Gold",
  ogdc: "OGDC",
  ptc: "PTC",
  "ralph-lauren": "Ralph Lauren",
  "safari-gardens": "Safari Gardens",
  samsung: "Samsung",
  sapphire: "Sapphire",
  tchibo: "Tchibo",
  "ted-baker": "Ted Baker",
  "tommy-bahama": "Tommy Bahama",
  "tommy-hilfiger": "Tommy Hilfiger",
  "total-parco": "Total Parco",
  umt: "UMT",
  "union-developers": "Union Developers",
  "volka-foods": "Volka Foods",
};
