const ROOT = "/mobile-assets";

export function encodeMobileAssetPath(path: string) {
  return encodeURI(path).replaceAll("&", "%26");
}

export const MOBILE_HOME = {
  heroVideo: `${ROOT}/Home Page/1. Home Page Video 43 Sec Mb.mp4`,
  processVideo: `${ROOT}/Home Page/2. How We Make It 43 Sec Mb.mp4`,
  contactImage: `${ROOT}/Home Page/6. Contact Vantage/V Building Night Mb.jpg`,
  printTech: {
    offset: `${ROOT}/Home Page/3. Five Print Technologies/Offset Mb.jpg`,
    "uv-offset": `${ROOT}/Home Page/3. Five Print Technologies/UV Offset Mb.jpg`,
    flexo: `${ROOT}/Home Page/3. Five Print Technologies/Flexo Mb.jpg`,
    screen: `${ROOT}/Home Page/3. Five Print Technologies/Screen Mb.jpg`,
    digital: `${ROOT}/Home Page/3. Five Print Technologies/Digital Mb.jpg`,
  },
  brief: [
    `${ROOT}/Home Page/5. Vantage in Brief/Sheet Analysis 1 MB.jpg`,
    `${ROOT}/Home Page/5. Vantage in Brief/Colour Management 2 Mb.jpg`,
    `${ROOT}/Home Page/5. Vantage in Brief/Colaboration 3 Mb.jpg`,
    `${ROOT}/Home Page/5. Vantage in Brief/Die Cutting 4 Mb.jpg`,
    `${ROOT}/Home Page/5. Vantage in Brief/Lamination 5 Mb.jpg`,
    `${ROOT}/Home Page/5. Vantage in Brief/Sheet Analysis 6 Mb.jpg`,
    `${ROOT}/Home Page/5. Vantage in Brief/Warehouse 7 Mb.jpg`,
    `${ROOT}/Home Page/5. Vantage in Brief/F&G 8 Mb.jpg`,
    `${ROOT}/Home Page/5. Vantage in Brief/Design Dept 9 Mb.jpg`,
    `${ROOT}/Home Page/5. Vantage in Brief/Flexo 10 MB.jpg`,
  ],
} as const;

export const MOBILE_TEAM_IMAGES: Record<string, string> = {
  "Adnan Bashir": `${ROOT}/Home Page/4. People Behind the Work/Adnan Bashir Founder & CEO.jpeg`,
  "Ali Touqir": `${ROOT}/Home Page/4. People Behind the Work/Ali Touqeer General Manager Sales.jpg`,
  "Amer Nawaz": `${ROOT}/Home Page/4. People Behind the Work/Amer Nawaz CFO.jpg`,
  "Imbesat Adnan": `${ROOT}/Home Page/4. People Behind the Work/Imbesat Adnan Manager Marketing.jpg`,
  "Mian Usman": `${ROOT}/Home Page/4. People Behind the Work/Mian Usman Sr. Manager Sales.jpg`,
  "Zubair Alam": `${ROOT}/Home Page/4. People Behind the Work/Zubair Alam Manager Sales.jpg`,
  "Naveed Bhatti": `${ROOT}/Home Page/4. People Behind the Work/Naveed Bhatti Manager Sales.jpg`,
  "Adnan Ahmed": `${ROOT}/Home Page/4. People Behind the Work/Adnan Ahmed Manager Sales.jpg`,
  "Qasim Raza": `${ROOT}/Home Page/4. People Behind the Work/Qasim Raza Manager Creative & Dsign.jpg`,
  "Syed Asmer Mahmood": `${ROOT}/Home Page/4. People Behind the Work/Asmer Mahmood Manager Pre Press.jpg`,
  "Arusha Adnan": `${ROOT}/Home Page/4. People Behind the Work/Arusha Ismail Product Designer.jpg`,
  "Alian Hafeez": `${ROOT}/Home Page/4. People Behind the Work/Alian Hafeez Executive Sales.jpg`,
};

export const MOBILE_WORK_HERO = [
  { src: `${ROOT}/Work/Landing Page/1. Cosmetics Mb.mp4`, type: "video" },
  { src: `${ROOT}/Work/Landing Page/2. Real Estage Mb.jpg`, type: "image" },
  { src: `${ROOT}/Work/Landing Page/3. Perfumes Mb.mp4`, type: "video" },
  { src: `${ROOT}/Work/Landing Page/4. Vantage Boxes Mb.jpg`, type: "image" },
  { src: `${ROOT}/Work/Landing Page/5 Pharma Mb.jpg`, type: "image" },
  { src: `${ROOT}/Work/Landing Page/6 MCB An. Rep. Mb.jpg`, type: "image" },
  { src: `${ROOT}/Work/Landing Page/7. Golden Book Mb.jpg`, type: "image" },
  { src: `${ROOT}/Work/Landing Page/8. Home Textile Mb.jpg`, type: "image" },
  { src: `${ROOT}/Work/Landing Page/9. Label Mb.jpg`, type: "image" },
  { src: `${ROOT}/Work/Landing Page/10. Car Brochure Mb.jpg`, type: "image" },
] as const;

export const MOBILE_WORK_COVERS: Record<string, string> = {
  "cosmetic-packaging": `${ROOT}/Work/Browse By Catagory/Cosmatics Packaging Mb.jpeg`,
  "perfume-packaging": `${ROOT}/Work/Browse By Catagory/Perfume Packaging Mb.jpg`,
  "pharmaceutical-packaging": `${ROOT}/Work/Browse By Catagory/Pharma Packaging Mb.jpg`,
  "home-and-textiles": `${ROOT}/Work/Browse By Catagory/Home Textile Packaging Mb.jpg`,
  "product-and-gift-boxes": `${ROOT}/Work/Browse By Catagory/Product & Gift Boxes Mb.jpg`,
  "labels-and-sleeves": `${ROOT}/Work/Browse By Catagory/Label & Sleeves. Mb. jpeg.jpg`,
  "annual-reports": `${ROOT}/Work/Landing Page/6 MCB An. Rep. Mb.jpg`,
  "books-and-publications": `${ROOT}/Work/Browse By Catagory/Books & Publications Mb.jpg`,
  "brochure-and-catalogues": `${ROOT}/Work/Browse By Catagory/Brochures & Catalogues Mb.jpeg`,
};

export const MOBILE_WORK_PROJECTS: Record<string, readonly string[]> = {
  "cosmetic-packaging": [
    `${ROOT}/Work/Browse By Catagory/Cosmatics Packaging/1. Golden Pearl Beauty Cream.jpeg`,
    `${ROOT}/Work/Browse By Catagory/Cosmatics Packaging/2. Fresh & White Beauty Cream.jpeg`,
    `${ROOT}/Work/Browse By Catagory/Cosmatics Packaging/3. Hello Hair Colour.jpeg`,
    `${ROOT}/Work/Browse By Catagory/Cosmatics Packaging/4. Goree Gold Beauty Cream.jpeg`,
    `${ROOT}/Work/Browse By Catagory/Cosmatics Packaging/5. Parley Herbal Beauty Cream.jpeg`,
    `${ROOT}/Work/Browse By Catagory/Cosmatics Packaging/6. Oxygene Gold Beauty Cream.jpeg`,
    `${ROOT}/Work/Browse By Catagory/Cosmatics Packaging/7. Golden Pearl Soap .jpeg`,
    `${ROOT}/Work/Browse By Catagory/Cosmatics Packaging/8. Dr. Snow White Beauty Cream.jpeg`,
    "/portfolio/cosmetics/nisa-naturals-soap.jpg",
    `${ROOT}/Work/Browse By Catagory/Cosmatics Packaging/10. Kanza Beauty Cream.jpeg`,
    `${ROOT}/Work/Browse By Catagory/Cosmatics Packaging/11. Bliss Gold Cream.jpeg`,
    `${ROOT}/Work/Browse By Catagory/Cosmatics Packaging/12. Goree Ubtan Packaging.jpeg`,
  ],
  "perfume-packaging": [
    `${ROOT}/Work/Browse By Catagory/Pefume Packaging/1. Quinn Eau De Perfum Mb.jpeg`,
    `${ROOT}/Work/Browse By Catagory/Pefume Packaging/2. Infinity Sultan Al Bakhtoor Mb.jpeg`,
    `${ROOT}/Work/Browse By Catagory/Pefume Packaging/3. Infinity Romeo Mauve Eau De Perfum Mb.jpeg`,
    `${ROOT}/Work/Browse By Catagory/Pefume Packaging/4. Broche Dizze Vaporisateur Natural Spray Mb.jpeg`,
    `${ROOT}/Work/Browse By Catagory/Pefume Packaging/5. Infinity Wisper Vaporisateur Natural Spray Mb.jpeg`,
    `${ROOT}/Work/Browse By Catagory/Pefume Packaging/6. Infinity Blooming Eau De Perfum Mb.jpeg`,
    `${ROOT}/Work/Browse By Catagory/Pefume Packaging/7. BlueRush Perfume Spray Mb.jpeg`,
    `${ROOT}/Work/Browse By Catagory/Pefume Packaging/8. Viceroy Velvet Mb.jpeg`,
    `${ROOT}/Work/Browse By Catagory/Pefume Packaging/9. Xclusive Collection Blossom Vaporisateur Spray Mb.jpeg`,
    `${ROOT}/Work/Browse By Catagory/Pefume Packaging/10. Quinn Vaporisateur Spray Mb.jpeg`,
    `${ROOT}/Work/Browse By Catagory/Pefume Packaging/11. Oud Ishq Eau de Toilette Mb.jpeg`,
    `${ROOT}/Work/Browse By Catagory/Pefume Packaging/12. M 25 Chalet Paris Vaporisateur Spray Mb.jpeg`,
  ],
  "pharmaceutical-packaging": [
    `${ROOT}/Work/Browse By Catagory/Pharmaceutical Packaging/1. Indrop D Vitamin D3 Neutro Pharma Mb.png`,
    `${ROOT}/Work/Browse By Catagory/Pharmaceutical Packaging/2. Famifol Martsons Pharma Mb.jpeg`,
    `${ROOT}/Work/Browse By Catagory/Pharmaceutical Packaging/3. Code Oral Drps Nurture Pharma Mb.jpeg`,
    `${ROOT}/Work/Browse By Catagory/Pharmaceutical Packaging/4. G Pro Drinkable High Nutrition Mb.jpeg`,
    `${ROOT}/Work/Browse By Catagory/Pharmaceutical Packaging/5. Cool Styling Hair Gel Ecrin Enterprises Mb.jpeg`,
    `${ROOT}/Work/Browse By Catagory/Pharmaceutical Packaging/6. Big Grow Syrup Nutrifactor Mb.jpeg`,
    `${ROOT}/Work/Browse By Catagory/Pharmaceutical Packaging/7. E+ & Omega Fish Oil Capsule Hi-Nutrition Mb.jpeg`,
    `${ROOT}/Work/Browse By Catagory/Pharmaceutical Packaging/8. Folinur Nurture Pharma Mb.jpeg`,
    `${ROOT}/Work/Browse By Catagory/Pharmaceutical Packaging/9. Tryception Nutrifactor Mb.jpeg`,
    `${ROOT}/Work/Browse By Catagory/Pharmaceutical Packaging/10.Optiano Contact Lens Solution Unique Visual System.jpeg`,
    `${ROOT}/Work/Browse By Catagory/Pharmaceutical Packaging/11. D-Sunscreen SPF 50 Nutrifactor Mb.jpeg`,
    `${ROOT}/Work/Browse By Catagory/Pharmaceutical Packaging/12. Ultima Contact Lens Solution Lapis Lazuli Int. NV Mb.jpeg`,
  ],
  "home-and-textiles": [
    `${ROOT}/Work/Browse By Catagory/Home Textile Packaging/1. Abstract Duvel Cover Set Blubellgray Mb.jpeg`,
    `${ROOT}/Work/Browse By Catagory/Home Textile Packaging/2. Antique Flowers Comfortor Set Bebejan Mb.jpeg`,
    `${ROOT}/Work/Browse By Catagory/Home Textile Packaging/3. Lacoste Signature Collection Mb.jpeg`,
    `${ROOT}/Work/Browse By Catagory/Home Textile Packaging/4.Nautica Home Bedding Mb.jpeg`,
    `${ROOT}/Work/Browse By Catagory/Home Textile Packaging/5. Tommy Bahama Beddings Mb.jpeg`,
    `${ROOT}/Work/Browse By Catagory/Home Textile Packaging/6. Canne Bedding Bluebellgray Mb.jpeg`,
    `${ROOT}/Work/Browse By Catagory/Home Textile Packaging/7. Laura Ashley Beddings Mb.jpeg`,
    `${ROOT}/Work/Browse By Catagory/Home Textile Packaging/8. Pure Collection Bathrobe MK Home Mb.jpeg`,
    `${ROOT}/Work/Browse By Catagory/Home Textile Packaging/9. Next Beddings MB.jpeg`,
  ],
  "product-and-gift-boxes": [
    `${ROOT}/Work/Browse By Catagory/Product & Gift Boxes/1. Gift Box Vantage Mb.jpeg`,
    `${ROOT}/Work/Browse By Catagory/Product & Gift Boxes/2. Phone & Batery bundle Box Samsung Mb.jpg`,
    `${ROOT}/Work/Browse By Catagory/Product & Gift Boxes/3. Phone Box Samsung Mb.jpeg`,
    `${ROOT}/Work/Browse By Catagory/Product & Gift Boxes/4. Product Box Dynasty MB.jpeg`,
    `${ROOT}/Work/Browse By Catagory/Product & Gift Boxes/5. Gift Box Chenab Group Mb.jpeg`,
    `${ROOT}/Work/Browse By Catagory/Product & Gift Boxes/6. Gift Box Quinn Cosmatics Mb.jpeg`,
    `${ROOT}/Work/Browse By Catagory/Product & Gift Boxes/7. Gift Hand Bag Nishat Linen Mb.jpeg`,
    `${ROOT}/Work/Browse By Catagory/Product & Gift Boxes/8. Gift Box Aimen Haider Mb.jpeg`,
    `${ROOT}/Work/Browse By Catagory/Product & Gift Boxes/9. Gift Box Synergy Mb.jpeg`,
    `${ROOT}/Work/Browse By Catagory/Product & Gift Boxes/10. Gift Box Vantage Mb.jpeg`,
    `${ROOT}/Work/Browse By Catagory/Product & Gift Boxes/11. Product Box Lay's Mb.jpeg`,
    `${ROOT}/Work/Browse By Catagory/Product & Gift Boxes/12. Product Box Airox Mb.jpeg`,
  ],
  "labels-and-sleeves": [
    `${ROOT}/Work/Browse By Catagory/Labels & Sleeves/Body Mist Label Kulaj Mb.jpeg`,
    `${ROOT}/Work/Browse By Catagory/Labels & Sleeves/Cologne Label Nexton Mb.jpeg`,
    `${ROOT}/Work/Browse By Catagory/Labels & Sleeves/Cream Label Due Gold Mb.jpeg`,
    `${ROOT}/Work/Browse By Catagory/Labels & Sleeves/Cream Label Goree Cosmatics Mb.jpeg`,
    `${ROOT}/Work/Browse By Catagory/Labels & Sleeves/Cream Label Kayenat Mb.jpeg`,
    `${ROOT}/Work/Browse By Catagory/Labels & Sleeves/Cream Label Zerwa Mb.jpeg`,
    `${ROOT}/Work/Browse By Catagory/Labels & Sleeves/Juice Bottle Sleeve Nestle Mb.jpeg`,
    `${ROOT}/Work/Browse By Catagory/Labels & Sleeves/Shampoo Label Goree Cosmatics Mb.jpeg`,
  ],
  "annual-reports": [
    `${ROOT}/Work/Browse By Catagory/Annual Reports/Annual Report 2020 Lucky Cement Mb.png`,
    `${ROOT}/Work/Browse By Catagory/Annual Reports/Annual Report 2024 FFC Mb.jpeg`,
    `${ROOT}/Work/Browse By Catagory/Annual Reports/Annual Report 2024 MCB Mb.jpeg`,
    `${ROOT}/Work/Browse By Catagory/Annual Reports/Annual Report 2024 OGDC Mb.jpeg`,
    `${ROOT}/Work/Browse By Catagory/Annual Reports/Annual Report 2025 Fatima Fertilizer Mb.jpeg`,
    `${ROOT}/Work/Browse By Catagory/Annual Reports/Annual Report 2025 Fauji Cement Mb.jpeg`,
    `${ROOT}/Work/Browse By Catagory/Annual Reports/Annual Report 2025 FFC Mb.jpeg`,
    `${ROOT}/Work/Browse By Catagory/Annual Reports/Annual Report 2025 Interloop Mb.jpeg`,
    `${ROOT}/Work/Browse By Catagory/Annual Reports/Annual Report 2025 PTC Mb.jpeg`,
    `${ROOT}/Work/Browse By Catagory/Annual Reports/Annual Report 2025 Wateen Mb.jpeg`,
    `${ROOT}/Work/Browse By Catagory/Annual Reports/Management Report 2022 Nestle Mb.jpeg`,
  ],
  "books-and-publications": [
    "/portfolio/books/coffee-table-book-zafarullah.jpg",
    `${ROOT}/Work/Browse By Catagory/Books & Publications/Coffee Table Book, Aisha Khalid Mb.jpeg`,
    `${ROOT}/Work/Browse By Catagory/Books & Publications/Coffee Table Book, RM Naeem Studios Mb.jpeg`,
    `${ROOT}/Work/Browse By Catagory/Books & Publications/Company Profile Vantage Mb.jpeg`,
    `${ROOT}/Work/Browse By Catagory/Books & Publications/Magazine Rozee.Pk Mb.jpeg`,
    `${ROOT}/Work/Browse By Catagory/Books & Publications/Perpetual Diary Allied Bank Ltd.Mb.jpeg`,
    `${ROOT}/Work/Browse By Catagory/Books & Publications/Pocket DIary Vantage Mb.jpeg`,
    `${ROOT}/Work/Browse By Catagory/Books & Publications/The Rausing Legacy, Packages Ltd Mb.jpeg`,
  ],
  "brochure-and-catalogues": [
    "/portfolio/brochures/fashion-catalogue-asim-jofa.jpg",
    `${ROOT}/Work/Browse By Catagory/Brochures & Catalogues/Car Brochure Hyundai Nishat Mb.jpeg`,
    `${ROOT}/Work/Browse By Catagory/Brochures & Catalogues/Fashion Catalogue, Almirah Mb.jpeg`,
    `${ROOT}/Work/Browse By Catagory/Brochures & Catalogues/Fashion Catalogue, Nishat Linen Mb.jpeg`,
    `${ROOT}/Work/Browse By Catagory/Brochures & Catalogues/Fashion Catalogue, Sapphire Mb.jpeg`,
    `${ROOT}/Work/Browse By Catagory/Brochures & Catalogues/Fashion Catalogue, Sobia Nazir Mb.jpeg`,
    `${ROOT}/Work/Browse By Catagory/Brochures & Catalogues/Fashion Magazine, By The Way MB.jpeg`,
    `${ROOT}/Work/Browse By Catagory/Brochures & Catalogues/Furniture Catalogue, Interwood Mb.jpeg`,
    `${ROOT}/Work/Browse By Catagory/Brochures & Catalogues/Makeup Catalogue, Luscious Cosmatics Mb.jpeg`,
    `${ROOT}/Work/Browse By Catagory/Brochures & Catalogues/Product Brochure, Golden Pearl Mb.jpeg`,
    `${ROOT}/Work/Browse By Catagory/Brochures & Catalogues/Product Brochure, Hanif Jewlers Mb.jpeg`,
    `${ROOT}/Work/Browse By Catagory/Brochures & Catalogues/Product Catalogue, J.Mb.jpeg`,
  ],
};

export const MOBILE_ABOUT: Record<string, string> = {
  hero: `${ROOT}/About Vantage/Landing Page Photo Mb.jpg`,
  studio: `${ROOT}/About Vantage/CEO Office Vantage Mb.jpg`,
  "design-studio": `${ROOT}/About Vantage/Our Begining/Vantage Design Studio 2011 Mb.jpg`,
  celebration: `${ROOT}/About Vantage/Our Begining/Creative Manager's birthday Vantage Studio, Lahore 2012 Mb.jpg`,
  production: `${ROOT}/About Vantage/Our Begining/Production Team, Vantage 2008 Mb.jpg`,
  offset: `${ROOT}/About Vantage/Our Begining/Offset Operators, Vantage 2005 Mb.jpg`,
  "master-binder": `${ROOT}/About Vantage/Our Begining/Asif Khan, Master Binder Vantage 2004 Mb.jpg`,
  "green-day": `${ROOT}/About Vantage/Our Begining/Environment Day, Vantage 2004 Mb.jpg`,
  "manzoor-ahmed": `${ROOT}/About Vantage/People Who Built Vantage/Manzoor Ahmed.jpg`,
  "asif-khan": `${ROOT}/About Vantage/People Who Built Vantage/Asif Khan.jpg`,
  "muhammad-hafeez": `${ROOT}/About Vantage/People Who Built Vantage/Muhammad Hafeez.jpg`,
  "aqeel-haider": `${ROOT}/About Vantage/People Who Built Vantage/Aqeel Haider.jpg`,
  "muhammad-shahid": `${ROOT}/About Vantage/People Who Built Vantage/Muhammad Shahid.jpg`,
  "zaheer-ahmed": `${ROOT}/About Vantage/People Who Built Vantage/Zaheer Ahmed.jpg`,
};

export const MOBILE_CAPABILITIES = {
  heroVideo: `${ROOT}/Capabilities/Landing Page Animation Mb.mp4`,
  workflowVideo: `${ROOT}/Capabilities/One Connected Workflow Animation Mb.mp4`,
  sections: {
    design: `${ROOT}/Capabilities/1. Design & Prepress Mb.jpg`,
    offset: `${ROOT}/Capabilities/2. Offset & UV Offset Mb.jpg`,
    flexo: `${ROOT}/Capabilities/3. Flexo Labels & Sleeves Mb.jpg`,
    screen: `${ROOT}/Capabilities/4. Screen Printing Mb.jpg`,
    digital: `${ROOT}/Capabilities/5. Digital Printing Mb.jpg`,
    finishing: `${ROOT}/Capabilities/6. Finishing & Converting Mb.jpg`,
  },
} as const;

export const MOBILE_START_PROJECT_VIDEO =
  `${ROOT}/Start A Project/Landing Page Animation Start A Project Mb.mp4`;
